site_name: Djapy
repo_url: https://github.com/Bishwas-py/djapy.git
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: green
      accent: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bishwas-py/djapy
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/djapy

copyright: |
  &copy; 2023 <a href="https://github.com/bishwas-py/djapy" target="_blank" rel="noopener" title="Djapy">Djapy</a>, MIT License

nav:
  - Introduction: index.md
  - Usage: usage.md
  - Swagger: swagger.md
  - Authentication: auth.md
  - Pagination: pagination.md
