from typing import Literal, List

ALLOW_METHODS_LITERAL = Literal["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD", "TRACE", "CONNECT"]
ALLOWED_METHODS = ALLOW_METHODS_LITERAL | List[ALLOW_METHODS_LITERAL]
